byrd-polar/fluid-earth

backend/file-conversions.js, backend/rabbit.js
Should allow for local testing of the Tera backend on Windows machines. Will still occasionally emit EPERM errors due to https://github.com/nodejs/node/issues/29481, but this will resolve itself through the default automatic-retry-after-five-minutes mechanism for each source.
=> Get Tera backend working on Windows

README.md
Allows for downloading of the era5monthy source.
=> Add missing CDS instructions for Tera backend

src/components/Notification.svelte
Before (mobile):
After (mobile):
Before (desktop):
After (desktop):
It also now remembers if the user dismissed the notification and won't show it again on subsequent visits.
=> Make welcome notification look and work nicer

src/map/particle/draw.vert, src/map/particle/simulator.js, src/map/particle/step.frag
Before:
After:
Removes the dependency on the EXT_color_buffer_float extension by using integer textures and bit conversions instead of float textures.
In more detail: some mobile devices (e.g. Galaxy S20) fail the [conformance test](https://registry.khronos.org/webgl/sdk/tests/conformance2/extensions/ext-color-buffer-float.html?webglVersion=2&quiet=0&quick=1) for the above extension and so render the particles incorrectly. By avoiding the extension, the majority of the rendering issues are hopefully fixed.
=> Fix particle rendering on some mobile devices

src/map/particle/simulator.js
Follow up to #11. More for completeness than anything else; extends our support to any device that supports the base WebGL2 spec without extensions.
=> Add fallback when linear filter is not available

src/map/projections/forward.glsl
Apparently clip not having an explicit default value causes the varying to take on seemingly random values, leading to some lines not being rendered some of the time as the map is being zoomed and panned
Only affected the equirectangular and stereographic projections and only on some Linux and Mac devices
=> Fix flickering of vector lines on some projections

index.html
Now uses Segoe UI for Windows and Noto Sans for most Linux distros
Fixes vertical alignment (text was too high) for Firefox on Linux
=> Update font stack

.github/workflows/tera-status-check.yml, README.md, backend/scripts/status.js
- Avoids duplicate emails/notifications when status is unchanged
- Removes manual snoozing (no longer needed)
- Removes README status badge
In effect, after this PR is merged we need to get out of the habit of ignoring the status check emails, as each one will now definitely have new information, good or bad.
Apologies for the spam I created while testing the new GitHub Action workflow :smiling_face_with_tear:.
=> Improve status check

index.html, src/App.svelte, src/main.js, src/utility.js
Noticeably reduces the time the splash screen remains visible on initial page load.
Tested on Firefox, Safari, and Chromium, all of which are a bit picky with regards to the CORS and credential modes for the fetch request to match the preload.
Seems to preserve the behavior of checking if the requested files were updated on the server before using the cached response previously declared by `headers: { 'Cache-Control': 'no-cache' }`.
=> Preload render-blocking resources

src/components/SideControls.svelte, src/overlays/Widgets.svelte
Was causing the legend widgets to fall off the screen when height was small, e.g. landscape mode on mobile
Also keeps side controls centered vertically instead of shifting when other widgets move
=> Fix side controls breaking rest of widget layout

backend/download.js, backend/file-conversions.js, backend/sources/era5monthly.js, backend/utility.js
Fixes both the original cause of failure and failures in general leaving behind temp files.
Issue in the CDS API has [been reported](https://jira.ecmwf.int/plugins/servlet/desk/portal/4/SD-76652). (Link is a note-to-self, requires login.)
=> Fix storage leak, take two

README.md, backend/download.js, backend/sources/oscar.js
This gets the existing data source working again and lays the foundation for upgrading to OSCAR v2 in the future.
Earthdata handles tokens a bit strangely — all tokens expire after 90 days so instead of an API key, the user's password is needed as an environmental variable to create tokens on the fly if needed. This is the same approach taken by https://github.com/podaac/data-subscriber.
=> Temporarily fix OSCAR data source

backend/datasets/oscar2-speed.js, backend/datasets/oscar2-velocity.js, backend/rabbit.js, backend/sources/oscar.js, backend/sources/oscar2-final.js, backend/sources/oscar2-interim.js, backend/sources/oscar2-nrt.js, backend/utility.js, src/intervals.js, src/map/data-projections/index.glsl, src/map/data-projections/index.js
This adds data sources for OSCAR version 2, which increases the spatial (0.33 degrees to 0.25 degrees) and time (~5 days to daily) resolutions compared to the original OSCAR.
Creates new datasets with a `v2` suffix to the name, which won't be accessible via the menus on the front-end for now. Will remove the suffix and rename the original OSCAR datasets once the initial run of all the sources is complete to avoid any time gaps. The initial run should take two to three days, after which I'll open a new PR for the dataset name changes.
The progress of the initial run can be tracked by opening the Developer-Only Tools menu in the local build and selecting the v2 datasets under "All Datasets".
=> Upgrade to OSCAR2 data source

backend/sources/oscar2-final.js, backend/utility.js
Was causing the wrong start and end dates to persist in the outputted dataset metadata; workaround is to put a single source (nrt) in charge of the metadata and skip writing to it for the other two.
Reverts non-working 30c21f829
=> Work around OSCAR2 data source race conditions

src/components/datasets/animations.js, src/datasets.js
Fixes animation filter not being specific enough and adds a special case for the oscar2-velocity dataset so that it can be displayed alongside sea surface temperatures by default
=> Fix OSCAR2 particle data not displaying correctly

backend/scripts/status.js
Missed a delay in the data, but that seems to be resolved now. This is a relatively low-priority check since OSCAR2 data files are never deleted, so a 4 day maximum delay is used (above the nominal 2 days).
https://forum.earthdata.nasa.gov/viewtopic.php?t=4383
=> Update status check for OSCAR to OSCAR2

backend/sources/geos.js
Avoid processing files that will be overwritten by newer ones until we are up to date, at which point this commit should be reverted.
=> Run GEOS in 'catch-up' mode

backend/datasets/pangaea-permafrost-lowres.js, backend/datasets/pangaea-permafrost.js, backend/sources/pangaea.js, src/components/datasets/DatasetInfo.svelte, src/components/datasets/topics.js, src/components/datasets/variables.js, src/map/data-projections/index.glsl, src/map/data-projections/index.js, src/units.js
Roughly ~4 times as small as the original using the 10 km resolution data instead of the 5 km resolution, which should help load times in transferring data to the GPU (38 MB vs 9.5 MB) on less powerful devices
=> Add a lower resolution permafrost dataset

backend/systemd/fev2r-tera.service
Change the time between restarts after failure from the default of 100ms to 1min so that we don't get the following error:
systemd[1]: start request repeated too quickly for fev2r-tera.service
Applying this PR on the prod server requires copying the `backend/systemd/fev2r-tera.service` to the path in `Loaded:` in the output of `systemctl status fev2r-tera.service`.
=> Avoid systemd service hitting burst limit

.github/workflows/tera-status-check.yml
Avoids warnings of using deprecated Node.js 16 actions
=> Update GitHub actions to use Node.js 20

backend/download.js
Currently FTPPRD is down, which normally wouldn't be a problem as we have logic to use NOMADS as a backup, but that was failing because our `content-type` check did not account for NOMADS not sending the header at all for `idx` files.
This fixes that and allows our GFS data to catch up again.
=> Fix GFS backup URL not working

backend/sources/gfs.js, backend/sources/gfswave.js, backend/sources/rtgssthr.js
Avoids the try-catch not reaching the catch when requests to FTPPRD time out, causing the data to stop flowing instead of using the backup NOMADS service. Now, the base_url will automatically be switched if 5 minutes have gone by without a successful update.
=> Use existing framework for FTPPRD/NOMADS retries
